services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    env_file: .env
    volumes:
      - mariadb_db:/var/lib/mysql 
    networks:
      - docker-network
    restart: on-failure
  nginx :
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    volumes:
      - wordpress_db:/var/www/html
    networks:
      - docker-network
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    env_file: .env
    volumes:
      - wordpress_db:/var/www/html
    networks:
      - docker-network
    depends_on:
        - mariadb
    restart: on-failure

volumes:
  wordpress_db :
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ylabser/data/wordpress

  mariadb_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ylabser/data/mariadb

networks:
  docker-network:
    driver: bridge
