events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name ylabser.42.fr;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name ylabser.42.fr localhost 127.0.0.1;

        ssl_certificate     /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        root /var/www/html;
        index index.html;
    }
}